spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://db:5432/db

  flyway:
    enabled: true
    locations: classpath:db/migration
